version: '3.5'
networks:
    default:
        driver: bridge
    god:
        external: true
services:
    nginx:
        restart: unless-stopped
        build:
          context: ./sources/nginx/
        networks:
            - god
        expose:
            - 80
        environment:
            - "VIRTUAL_HOST=api.cvpro.local"
            - "VIRTUAL_PORT=80"
            - "LETSENCRYPT_HOST=api.cvpro.local"
            - "LETSENCRYPT_EMAIL=admin@cvpro.co"
        volumes:
            - ../html/backend:/var/www/html/
            - ./sources/zoneinfo/Asia/Ho_Chi_Minh:/etc/localtime:ro
    nginx_frontend:
        restart: unless-stopped
        build:
          context: ./sources/nginx/
        networks:
            - god
        expose:
            - 80
        environment:
            - "VIRTUAL_HOST=cvpro.local,cvpro.co"
            - "VIRTUAL_PORT=80"
            - "LETSENCRYPT_HOST=cvpro.local,cvpro.co"
            - "LETSENCRYPT_EMAIL=admin@cvpro.co"
        volumes:
            - ../html/frontend/:/var/www/html/:cached
            - ./sources/zoneinfo/Asia/Ho_Chi_Minh:/etc/localtime:ro
    phpfpm:
        restart: unless-stopped
        build:
            context: ./sources/php-fpm/7.4.0
        deploy:
            replicas: 1
        networks:
            - god
        volumes:
            - ../html/backend:/var/www/html/:cached
            - ../html/backend/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ../html/backend/supervisor.d:/etc/supervisor/conf.d
            - ./sources/php-fpm/7.4.0/config/php-cli.ini:/usr/local/etc/php/php-cli.ini
            - ./sources/zoneinfo/Asia/Ho_Chi_Minh:/etc/localtime:ro
        command:
            - /bin/bash
            - -c
            - |
              /usr/bin/supervisord
        working_dir: /var/www/html/public_html
    redis:
        image: redis:6
        restart: always
        networks:
            - god
        volumes:
            - ./databases/redis/cvprodb:/data
    mongodb:
        image: 'bitnami/mongodb:latest' #4.2.15
        restart: always
        networks:
            - god
        ports:
            - 27017:27017
        environment:
            - MONGODB_SYSTEM_LOG_VERBOSITY=3
            - MONGODB_ENABLE_JOURNAL=true
            - MONGODB_USERNAME=cvprodb
            - MONGODB_PASSWORD=cvprodb@!2021
            - MONGODB_DATABASE=cvprodb
            - MONGODB_ROOT_PASSWORD=88888888
        volumes:
            - ./databases/mongodb/cvprodb/:/bitnami/mongodb
