version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy-Yk7PYx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sources/certs/:/etc/nginx/certs:ro
      - ./sources/vhost.d/:/etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion-Yk7PYx
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./sources/certs/:/etc/nginx/certs:rw"
networks:
  default:
    external:
      name: god
